export interface WordMeaning {
  pos: string
  def: string
}

export const DEFINITIONS: Record<string, WordMeaning> = {
  apple: { pos: 'noun', def: 'a round fruit with red, green, or yellow skin and crisp flesh' },
  chair: { pos: 'noun', def: 'a seat with a back, made for one person' },
  sound: { pos: 'noun', def: 'something you hear, caused by vibrations travelling through air' },
  world: { pos: 'noun', def: 'the planet we live on, including all its people and places' },
  plant: { pos: 'noun', def: 'a living thing that grows in soil and makes food from sunlight' },
  crane: { pos: 'noun', def: 'a large bird with long legs and a long neck' },
  storm: { pos: 'noun', def: 'a period of violent weather with strong wind, rain, or thunder' },
  house: { pos: 'noun', def: 'a building where people live' },
  mouse: { pos: 'noun', def: 'a small rodent with a pointed nose and a long thin tail' },
  horse: { pos: 'noun', def: 'a large strong animal with a mane, kept for riding and pulling loads' },
  water: { pos: 'noun', def: 'the clear liquid that falls as rain and fills rivers and seas' },
  paper: { pos: 'noun', def: 'thin flat sheets made from wood pulp, used for writing and printing' },
  table: { pos: 'noun', def: 'a piece of furniture with a flat top and legs' },
  glass: { pos: 'noun', def: 'a hard, clear material that breaks easily, used in windows and cups' },
  stone: { pos: 'noun', def: 'a hard piece of rock, often small enough to pick up' },
  brick: { pos: 'noun', def: 'a hard block of baked clay used for building walls' },
  cloud: { pos: 'noun', def: 'a white or grey mass of tiny water droplets floating in the sky' },
  river: { pos: 'noun', def: 'a large natural stream of water flowing toward the sea' },
  ocean: { pos: 'noun', def: 'a vast body of salt water covering much of the earth' },
  beach: { pos: 'noun', def: 'a strip of sand or pebbles beside the sea or a lake' },
  grass: { pos: 'noun', def: 'a green plant with thin leaves that covers lawns and fields' },
  bread: { pos: 'noun', def: 'a baked food made from flour, water, and yeast' },
  sugar: { pos: 'noun', def: 'a sweet white or brown substance used to flavor food and drinks' },
  spice: { pos: 'noun', def: 'a strong-tasting plant part, like pepper or cinnamon, used to flavor food' },
  bacon: { pos: 'noun', def: 'thin salted slices of pork that are fried or grilled' },
  candy: { pos: 'noun', def: 'a sweet treat made mostly of sugar' },
  lemon: { pos: 'noun', def: 'a sour yellow citrus fruit' },
  mango: { pos: 'noun', def: 'a sweet, juicy tropical fruit with orange flesh and a large stone' },
  grape: { pos: 'noun', def: 'a small, juicy round fruit that grows in bunches and makes wine' },
  melon: { pos: 'noun', def: 'a large, sweet, juicy fruit with a thick rind and many seeds' },
  peach: { pos: 'noun', def: 'a soft, round fruit with fuzzy skin and a large pit' },
  berry: { pos: 'noun', def: 'a small, juicy fruit with thin skin and many tiny seeds' },
  onion: { pos: 'noun', def: 'a round vegetable with a sharp smell that can make your eyes water' },
  herbs: { pos: 'noun', def: 'leafy plants used to add flavor to food or make medicine' },
  shirt: { pos: 'noun', def: 'a piece of clothing for the upper body, usually with sleeves and buttons' },
  pants: { pos: 'noun', def: 'clothing that covers each leg separately, from the waist down' },
  dress: { pos: 'noun', def: 'a one-piece garment with a skirt, worn mostly by women and girls' },
  jeans: { pos: 'noun', def: 'casual trousers made of strong blue cotton fabric' },
  socks: { pos: 'noun', def: 'coverings worn on the feet, usually inside shoes' },
  scarf: { pos: 'noun', def: 'a long piece of cloth worn around the neck for warmth or style' },
  glove: { pos: 'noun', def: 'a covering for the hand with separate parts for each finger' },
  boots: { pos: 'noun', def: 'strong footwear that covers the foot and part of the leg' },
  shoes: { pos: 'noun', def: 'coverings for the feet, worn when walking outdoors' },
  cloak: { pos: 'noun', def: 'a loose outer garment without sleeves that hangs from the shoulders' },
  heart: { pos: 'noun', def: 'the organ in your chest that pumps blood around the body' },
  brain: { pos: 'noun', def: 'the organ inside your head that controls thought and movement' },
  bones: { pos: 'noun', def: 'the hard white parts that make up the skeleton of the body' },
  blood: { pos: 'noun', def: 'the red liquid pumped around the body by the heart' },
  mouth: { pos: 'noun', def: 'the opening in the face used for eating and speaking' },
  teeth: { pos: 'noun', def: 'the hard white parts in the mouth used for biting and chewing' },
  elbow: { pos: 'noun', def: 'the joint where the arm bends in the middle' },
  wrist: { pos: 'noun', def: 'the joint that connects the hand to the arm' },
  ankle: { pos: 'noun', def: 'the joint that connects the foot to the leg' },
  thumb: { pos: 'noun', def: 'the short, thick finger on the side of the hand' },
  music: { pos: 'noun', def: 'pleasing sounds made by voices or instruments' },
  piano: { pos: 'noun', def: 'a large instrument played by pressing black and white keys' },
  dance: { pos: 'verb', def: 'to move your body in time to music' },
  drama: { pos: 'noun', def: 'a play or show about serious or emotional events' },
  movie: { pos: 'noun', def: 'a story told through moving pictures, shown in a cinema or on a screen' },
  novel: { pos: 'noun', def: 'a long book that tells an invented story' },
  story: { pos: 'noun', def: 'an account of real or imaginary events told to entertain' },
  poems: { pos: 'noun', def: 'pieces of writing that use rhythm and carefully chosen words to share feelings' },
  voice: { pos: 'noun', def: 'the sound you make when you speak or sing' },
  bring: { pos: 'verb', def: 'to carry or take something along to a place' },
  light: { pos: 'noun', def: 'the brightness from the sun or a lamp that lets us see' },
  night: { pos: 'noun', def: 'the dark part of the day, when the sun is down' },
  dream: { pos: 'noun', def: 'a series of images and feelings your mind creates while you sleep' },
  smile: { pos: 'noun', def: 'a happy look on the face, with the corners of the mouth turned up' },
  laugh: { pos: 'verb', def: 'to make happy sounds because something is funny' },
  tears: { pos: 'noun', def: 'drops of salty liquid that fall from the eyes when you cry' },
  happy: { pos: 'adjective', def: 'feeling pleased and full of joy' },
  angry: { pos: 'adjective', def: 'feeling strong displeasure or annoyance toward someone or something' },
  quiet: { pos: 'adjective', def: 'making little or no noise' },
  sharp: { pos: 'adjective', def: 'having a thin edge or point that can cut or pierce' },
  blunt: { pos: 'adjective', def: 'not sharp, having a dull edge or tip' },
  round: { pos: 'adjective', def: 'shaped like a circle or a ball' },
  small: { pos: 'adjective', def: 'not big in size or amount' },
  large: { pos: 'adjective', def: 'big in size, amount, or number' },
  giant: { pos: 'adjective', def: 'extremely big, much larger than usual' },
  heavy: { pos: 'adjective', def: 'weighing a lot and hard to lift' },
  solid: { pos: 'adjective', def: 'firm and hard, not a liquid or gas' },
  fresh: { pos: 'adjective', def: 'newly made or picked and not yet spoiled' },
  clean: { pos: 'adjective', def: 'free from dirt or stains' },
  dirty: { pos: 'adjective', def: 'covered with mud, dust, or stains' },
  smell: { pos: 'verb', def: 'to notice something through your nose' },
  taste: { pos: 'verb', def: 'to notice the flavor of food using your tongue' },
  sweet: { pos: 'adjective', def: 'having a sugary flavor like honey or candy' },
  spicy: { pos: 'adjective', def: 'flavored with hot, strong seasonings' },
  bland: { pos: 'adjective', def: 'mild and lacking a strong flavor' },
  salty: { pos: 'adjective', def: 'containing or tasting of salt' },
  earth: { pos: 'noun', def: 'the planet we live on, third from the sun' },
  space: { pos: 'noun', def: 'the vast area beyond our planet where the stars and moons are' },
  orbit: { pos: 'noun', def: 'the curved path of a moon or planet around a larger body' },
  comet: { pos: 'noun', def: 'an icy body in space that grows a glowing tail near the sun' },
  stars: { pos: 'noun', def: 'huge balls of glowing gas, seen as points of light in the night sky' },
  solar: { pos: 'adjective', def: 'relating to or powered by the sun' },
  lunar: { pos: 'adjective', def: 'relating to the moon' },
  globe: { pos: 'noun', def: 'a round model of the earth, or the earth itself' },
  peace: { pos: 'noun', def: 'a calm time without war, fighting, or noise' },
  anger: { pos: 'noun', def: 'a strong feeling of being upset and wanting to fight back' },
  brave: { pos: 'adjective', def: 'ready to face danger or pain without showing fear' },
  proud: { pos: 'adjective', def: 'feeling pleased about something you or others have done' },
  shame: { pos: 'noun', def: 'an uncomfortable feeling you get when you have done something wrong' },
  faith: { pos: 'noun', def: 'strong belief in someone or something, often without proof' },
  trust: { pos: 'noun', def: 'a firm belief that someone is honest and reliable' },
  doubt: { pos: 'noun', def: 'a feeling of not being sure about something' },
  worry: { pos: 'verb', def: 'to feel anxious about problems that might happen' },
  money: { pos: 'noun', def: 'coins and notes used to buy things' },
  bonus: { pos: 'noun', def: 'an extra reward or payment on top of what is expected' },
  wages: { pos: 'noun', def: 'regular payments a person gets for doing a job' },
  price: { pos: 'noun', def: 'the amount of money you must pay for something' },
  value: { pos: 'noun', def: 'how much something is worth or how useful it is' },
  worth: { pos: 'adjective', def: 'having a certain value, or good enough to deserve effort' },
  debts: { pos: 'noun', def: 'sums of money that people owe to others' },
  sales: { pos: 'noun', def: 'times when goods are sold, often at lower prices' },
  trade: { pos: 'verb', def: 'to buy, sell, or swap goods with others' },
  store: { pos: 'noun', def: 'a place where goods are sold, or a supply kept for later use' },
  cabin: { pos: 'noun', def: 'a small wooden house, often in the woods or mountains' },
  tower: { pos: 'noun', def: 'a tall, narrow building or part of a building' },
  fence: { pos: 'noun', def: 'a barrier of posts and wire or boards around a yard or field' },
  porch: { pos: 'noun', def: 'a covered area at the entrance of a house' },
  attic: { pos: 'noun', def: 'a space under the roof of a house, often used for storage' },
  floor: { pos: 'noun', def: 'the surface of a room that you walk on' },
  roofs: { pos: 'noun', def: 'the outer coverings on top of buildings that keep out rain' },
  walls: { pos: 'noun', def: 'upright structures that enclose or divide rooms and buildings' },
  rooms: { pos: 'noun', def: 'separate spaces inside a building, enclosed by walls' },
  couch: { pos: 'noun', def: 'a long, soft seat for several people' },
  shelf: { pos: 'noun', def: 'a flat board fixed to a wall for holding books or objects' },
  clock: { pos: 'noun', def: 'a device that shows what time it is' },
  lamps: { pos: 'noun', def: 'devices that give out light, often with a shade' },
  blind: { pos: 'adjective', def: 'unable to see' },
  knife: { pos: 'noun', def: 'a tool with a sharp blade and a handle, used for cutting' },
  spoon: { pos: 'noun', def: 'a tool with a small bowl on a handle, used for eating soup or stirring' },
  plate: { pos: 'noun', def: 'a flat dish that you eat food from' },
  bowls: { pos: 'noun', def: 'deep round dishes used for soup, cereal, or salad' },
  pizza: { pos: 'noun', def: 'a flat baked dough topped with tomato sauce, cheese, and other toppings' },
  sauce: { pos: 'noun', def: 'a thick liquid poured over food to add flavor' },
  toast: { pos: 'noun', def: 'slices of bread browned by heating' },
  juice: { pos: 'noun', def: 'the liquid squeezed from fruit or vegetables' },
  drink: { pos: 'verb', def: 'to swallow a liquid' },
  flour: { pos: 'noun', def: 'a fine powder made from ground grain, used for baking' },
  yeast: { pos: 'noun', def: 'a tiny fungus that makes dough rise and turns sugar into alcohol' },
  dough: { pos: 'noun', def: 'a soft mixture of flour and water that is baked into bread' },
  baker: { pos: 'noun', def: 'a person who makes and sells bread and cakes' },
  maker: { pos: 'noun', def: 'a person or company that creates or builds something' },
  clerk: { pos: 'noun', def: 'a person who does office work or serves customers in a shop' },
  nurse: { pos: 'noun', def: 'a person trained to care for sick or injured people' },
  actor: { pos: 'noun', def: 'a person who plays a role in a play, film, or show' },
  teach: { pos: 'verb', def: 'to help someone gain knowledge or a skill' },
  learn: { pos: 'verb', def: 'to gain knowledge or skill by studying or practice' },
  study: { pos: 'verb', def: 'to spend time reading and thinking to gain knowledge' },
  class: { pos: 'noun', def: 'a group of students taught together, or the lesson they attend' },
  grade: { pos: 'noun', def: 'a mark showing how well a student did, or a level at school' },
  exams: { pos: 'noun', def: 'formal tests of what a student knows' },
  tests: { pos: 'noun', def: 'short checks of knowledge, skill, or quality' },
  books: { pos: 'noun', def: 'sets of printed pages bound together, for reading' },
  pages: { pos: 'noun', def: 'single sheets of paper in a book, or one side of such a sheet' },
  games: { pos: 'noun', def: 'activities with rules that people play for fun or to win' },
  chess: { pos: 'noun', def: 'a board game for two players with sixteen pieces each, including a king' },
  board: { pos: 'noun', def: 'a flat piece of wood or other material used for a particular purpose' },
  court: { pos: 'noun', def: 'a marked area for games like tennis, or a place where trials are held' },
  score: { pos: 'noun', def: 'the number of points a player or team has earned' },
  teams: { pos: 'noun', def: 'groups of people who play or work together' },
  coach: { pos: 'noun', def: 'a person who trains a player or team' },
  medal: { pos: 'noun', def: 'a small metal disc given as an award' },
  prize: { pos: 'noun', def: 'something given to the winner of a contest' },
  climb: { pos: 'verb', def: 'to go up something using your hands and feet' },
  throw: { pos: 'verb', def: 'to send something through the air with a movement of the arm' },
  catch: { pos: 'verb', def: 'to grab something that is moving through the air' },
  punch: { pos: 'verb', def: 'to hit someone or something with a closed fist' },
  kicks: { pos: 'noun', def: 'strikes made with the foot' },
  block: { pos: 'noun', def: 'a solid piece of wood, stone, or other material with flat sides' },
  guard: { pos: 'noun', def: 'a person who watches over a place or protects someone' },
  crazy: { pos: 'adjective', def: 'very silly, wild, or not sensible' },
  funny: { pos: 'adjective', def: 'causing people to laugh' },
  silly: { pos: 'adjective', def: 'playful and not serious, or lacking good sense' },
  weird: { pos: 'adjective', def: 'strange and hard to explain' },
  scary: { pos: 'adjective', def: 'causing fear' },
  lucky: { pos: 'adjective', def: 'having good things happen by chance' },
  dizzy: { pos: 'adjective', def: 'feeling as if everything is spinning around you' },
  sorry: { pos: 'adjective', def: 'feeling regret for something you have done' },
  sleep: { pos: 'verb', def: 'to rest with your eyes closed and your mind unaware' },
  awake: { pos: 'adjective', def: 'not sleeping' },
  tired: { pos: 'adjective', def: 'in need of rest or sleep' },
  fruit: { pos: 'noun', def: 'the sweet part of a plant that holds seeds, like an apple or a pear' },
  olive: { pos: 'noun', def: 'a small green or black fruit that is pressed to make oil' },
  beans: { pos: 'noun', def: 'edible seeds that grow in pods, like kidney or black ones' },
  beets: { pos: 'noun', def: 'round dark red root vegetables' },
  curry: { pos: 'noun', def: 'a dish cooked in a spicy sauce, popular in South Asia' },
  gravy: { pos: 'noun', def: 'a sauce made from meat juices, poured over meat and potatoes' },
  syrup: { pos: 'noun', def: 'a thick, sweet liquid poured over pancakes or desserts' },
  metal: { pos: 'noun', def: 'a hard, shiny material such as iron, gold, or copper' },
  steel: { pos: 'noun', def: 'a very strong metal made from iron and carbon' },
  brass: { pos: 'noun', def: 'a yellow metal made by mixing copper and zinc' },
  crown: { pos: 'noun', def: 'a circular headdress, often of gold, worn by a king or queen' },
  queen: { pos: 'noun', def: 'a woman who rules a country, or the wife of a king' },
  reign: { pos: 'noun', def: 'the period during which a king or queen rules' },
  royal: { pos: 'adjective', def: 'belonging to a king or queen' },
  noble: { pos: 'adjective', def: 'having high moral qualities, or born into the upper class' },
  lords: { pos: 'noun', def: 'men of high rank or with power over others' },
  baron: { pos: 'noun', def: 'a nobleman of the lowest rank, or a powerful business leader' },
  sword: { pos: 'noun', def: 'a weapon with a long metal blade and a handle' },
  armor: { pos: 'noun', def: 'protective metal covering worn by knights in battle' },
  spear: { pos: 'noun', def: 'a long weapon with a sharp point on a pole' },
  arrow: { pos: 'noun', def: 'a thin shaft with a pointed tip, shot from a bow' },
  blade: { pos: 'noun', def: 'the flat cutting edge of a knife or sword' },
  lance: { pos: 'noun', def: 'a long pole with a pointed head, carried by knights on horseback' },
  tiger: { pos: 'noun', def: 'a large wild cat with orange fur and black stripes' },
  eagle: { pos: 'noun', def: 'a large bird of prey with sharp eyesight and strong wings' },
  shark: { pos: 'noun', def: 'a large sea fish with sharp teeth and a triangular fin' },
  whale: { pos: 'noun', def: 'a huge mammal that lives in the sea and breathes through a blowhole' },
  zebra: { pos: 'noun', def: 'a wild African animal like a horse with black and white stripes' },
  camel: { pos: 'noun', def: 'a desert animal with one or two humps on its back' },
  sheep: { pos: 'noun', def: 'a farm animal with thick wool, kept for its fleece and meat' },
  goats: { pos: 'noun', def: 'farm animals with horns and beards that climb well and give milk' },
  snake: { pos: 'noun', def: 'a long, thin reptile with no legs' },
  bunny: { pos: 'noun', def: 'a child\'s word for a small rabbit with long ears' },
  puppy: { pos: 'noun', def: 'a young dog' },
  kitty: { pos: 'noun', def: 'a child\'s word for a cat, especially a young one' },
  otter: { pos: 'noun', def: 'a playful furry animal that swims well and eats fish' },
  koala: { pos: 'noun', def: 'a gray furry Australian animal that lives in gum trees' },
  panda: { pos: 'noun', def: 'a large black and white bear from China that eats bamboo' },
  bears: { pos: 'noun', def: 'large, heavy mammals with thick fur and strong claws' },
  foxes: { pos: 'noun', def: 'wild animals like small dogs with pointed faces and bushy tails' },
  birds: { pos: 'noun', def: 'animals with feathers and wings, most of which can fly' },
  heron: { pos: 'noun', def: 'a tall wading bird with long legs and a long neck' },
  robin: { pos: 'noun', def: 'a small songbird with a red or orange chest' },
  finch: { pos: 'noun', def: 'a small songbird with a short, strong beak for eating seeds' },
  raven: { pos: 'noun', def: 'a large black bird with a deep croaking call' },
  swans: { pos: 'noun', def: 'large white water birds with long graceful necks' },
  geese: { pos: 'noun', def: 'large water birds that honk and fly in V-shaped groups' },
  ducks: { pos: 'noun', def: 'water birds with flat beaks and webbed feet that quack' },
  quail: { pos: 'noun', def: 'a small, plump game bird with a short tail' },
  trout: { pos: 'noun', def: 'a freshwater fish with speckled skin, popular for angling' },
  perch: { pos: 'noun', def: 'a freshwater fish with spiny fins, or a branch where a bird rests' },
  squid: { pos: 'noun', def: 'a sea creature with a long soft body, eight arms, and two tentacles' },
  crabs: { pos: 'noun', def: 'sea creatures with a hard shell and pincers that walk sideways' },
  clams: { pos: 'noun', def: 'shellfish with two hinged shells that live buried in sand' },
  shell: { pos: 'noun', def: 'the hard outer covering of an egg, a nut, or a sea animal' },
  coral: { pos: 'noun', def: 'a hard, colorful substance made by tiny sea animals, forming reefs' },
  reefs: { pos: 'noun', def: 'ridges of rock or coral lying just below the sea surface' },
  waves: { pos: 'noun', def: 'moving ridges of water on the surface of the sea' },
  tides: { pos: 'noun', def: 'the regular rise and fall of the sea level each day' },
  lakes: { pos: 'noun', def: 'large bodies of water surrounded by land' },
  ponds: { pos: 'noun', def: 'small areas of still water, smaller than lakes' },
  creek: { pos: 'noun', def: 'a small stream or narrow inlet of water' },
  delta: { pos: 'noun', def: 'a triangle of land formed where a river splits before reaching the sea' },
  shore: { pos: 'noun', def: 'the land along the edge of the sea or a lake' },
  mount: { pos: 'verb', def: 'to climb up onto something, such as a horse or a platform' },
  hills: { pos: 'noun', def: 'raised areas of land, smaller than mountains' },
  cliff: { pos: 'noun', def: 'a steep rock face, especially beside the sea' },
  slope: { pos: 'noun', def: 'a surface that is tilted, with one end higher than the other' },
  peaks: { pos: 'noun', def: 'the pointed tops of mountains' },
  ridge: { pos: 'noun', def: 'a long, narrow raised strip of land along the top of a hill' },
  rocks: { pos: 'noun', def: 'hard natural materials that make up the earth, or large stones' },
  sands: { pos: 'noun', def: 'stretches of tiny grains of crushed rock, found on beaches and deserts' },
  dunes: { pos: 'noun', def: 'hills of sand piled up by the wind' },
  caves: { pos: 'noun', def: 'large hollow spaces underground or inside a hillside' },
  rains: { pos: 'noun', def: 'falls of water drops from the clouds' },
  winds: { pos: 'noun', def: 'natural movements of air across the earth\'s surface' },
  gusts: { pos: 'noun', def: 'sudden strong bursts of air' },
  frost: { pos: 'noun', def: 'a thin layer of tiny ice crystals that forms on cold surfaces' },
  snows: { pos: 'noun', def: 'falls of soft white flakes of frozen water' },
  sunny: { pos: 'adjective', def: 'bright with light from the sun' },
  windy: { pos: 'adjective', def: 'with a lot of moving air' },
  north: { pos: 'noun', def: 'the direction to your left when you face the rising sun' },
  south: { pos: 'noun', def: 'the direction opposite to the one a compass needle points to' },
  atlas: { pos: 'noun', def: 'a book of maps' },
  route: { pos: 'noun', def: 'the way you take to get from one place to another' },
  roads: { pos: 'noun', def: 'paved ways for cars and other vehicles to travel on' },
  paths: { pos: 'noun', def: 'narrow tracks for walking, made by feet' },
  train: { pos: 'noun', def: 'a series of linked carriages pulled along railway tracks' },
  plane: { pos: 'noun', def: 'a flying vehicle with wings and engines' },
  buses: { pos: 'noun', def: 'large vehicles that carry many passengers along set routes' },
  truck: { pos: 'noun', def: 'a large motor vehicle for carrying goods' },
  wagon: { pos: 'noun', def: 'a four-wheeled vehicle for carrying loads, pulled by animals or by hand' },
  cycle: { pos: 'noun', def: 'a series of events that repeat in the same order, or a bike' },
  metro: { pos: 'noun', def: 'an underground railway system in a city' },
  ferry: { pos: 'noun', def: 'a boat that carries people and vehicles across water' },
  yacht: { pos: 'noun', def: 'a sleek boat with sails or an engine, used for pleasure or racing' },
  bills: { pos: 'noun', def: 'written requests for payment, or paper money in some countries' },
  coins: { pos: 'noun', def: 'small flat round pieces of metal used as money' },
  cards: { pos: 'noun', def: 'small pieces of stiff paper used for games or for sending greetings' },
  bonds: { pos: 'noun', def: 'ties or connections that hold things or people together' },
  bench: { pos: 'noun', def: 'a long seat for several people, often outdoors' },
  stool: { pos: 'noun', def: 'a seat with legs but no back or arms' },
  desks: { pos: 'noun', def: 'tables for reading, writing, or working at' },
  paint: { pos: 'noun', def: 'a colored liquid spread on surfaces to decorate or protect them' },
  brush: { pos: 'noun', def: 'a tool with bristles for painting, cleaning, or tidying hair' },
  color: { pos: 'noun', def: 'a quality like red, blue, or green that you see with your eyes' },
  shape: { pos: 'noun', def: 'the outer form of something, like a circle or a square' },
  shade: { pos: 'noun', def: 'a cool, darker area where sunlight is blocked' },
  tones: { pos: 'noun', def: 'qualities of sounds or colors, or the attitude shown in a voice' },
  black: { pos: 'adjective', def: 'of the darkest color, like coal or a starless night' },
  white: { pos: 'adjective', def: 'of the color of fresh snow or milk' },
  green: { pos: 'adjective', def: 'of the color of grass and leaves' },
  brown: { pos: 'adjective', def: 'of the color of chocolate or soil' },
  ivory: { pos: 'noun', def: 'a creamy white color, or the hard material of elephant tusks' },
  beige: { pos: 'noun', def: 'a pale sandy-brown color' },
  amber: { pos: 'noun', def: 'a hard, yellowish-orange resin from ancient trees, used in jewelry' },
  khaki: { pos: 'noun', def: 'a dull yellowish-brown color, or strong cloth of that color' },
  denim: { pos: 'noun', def: 'strong blue cotton cloth used for making jeans' },
  bored: { pos: 'adjective', def: 'feeling tired and uninterested because nothing is exciting' },
  eager: { pos: 'adjective', def: 'very keen and excited to do or have something' },
  timid: { pos: 'adjective', def: 'shy and easily frightened' },
  rough: { pos: 'adjective', def: 'not smooth, with a bumpy or uneven surface' },
  tough: { pos: 'adjective', def: 'strong and hard to break, cut, or defeat' },
  plain: { pos: 'adjective', def: 'simple, with no decoration or extra features' },
  fancy: { pos: 'adjective', def: 'elaborate and decorated rather than simple' },
  cheap: { pos: 'adjective', def: 'low in price and costing little money' },
  thick: { pos: 'adjective', def: 'having a large distance between two opposite sides' },
  broad: { pos: 'adjective', def: 'wide from one side to the other' },
  stale: { pos: 'adjective', def: 'no longer fresh, such as bread that has gone dry and hard' },
  crisp: { pos: 'adjective', def: 'firm, dry, and making a snapping sound when bitten' },
  juicy: { pos: 'adjective', def: 'full of liquid when you bite into it' },
  moist: { pos: 'adjective', def: 'slightly wet' },
  dried: { pos: 'adjective', def: 'having had the water removed, such as raisins or herbs' },
  fried: { pos: 'adjective', def: 'cooked in hot oil or fat' },
  grill: { pos: 'verb', def: 'to cook food over or under direct heat' },
  roast: { pos: 'verb', def: 'to cook food in an oven with dry heat' },
  broil: { pos: 'verb', def: 'to cook food with strong heat from above' },
  phone: { pos: 'noun', def: 'a device used to talk with people far away' },
  radio: { pos: 'noun', def: 'a device that receives sound broadcast through the air' },
  video: { pos: 'noun', def: 'a recording of moving pictures and sound' },
  photo: { pos: 'noun', def: 'a picture made with a camera' },
  robot: { pos: 'noun', def: 'a machine that can carry out tasks on its own' },
  laser: { pos: 'noun', def: 'a very narrow, powerful beam of light' },
  drone: { pos: 'noun', def: 'an aircraft without a pilot, flown by remote control' },
  motor: { pos: 'noun', def: 'a machine that turns energy into movement' },
  wheel: { pos: 'noun', def: 'a round object that turns around its center, helping things roll' },
  brake: { pos: 'noun', def: 'a device that slows down or stops a vehicle' },
  tires: { pos: 'noun', def: 'rubber rings around the wheels of vehicles' },
  spark: { pos: 'noun', def: 'a tiny bright flash of fire or electricity' },
  fuels: { pos: 'noun', def: 'materials like coal or gasoline that are burned to make energy' },
  power: { pos: 'noun', def: 'strength or energy, or the ability to control things' },
  wires: { pos: 'noun', def: 'thin strands of metal that carry electricity' },
  cable: { pos: 'noun', def: 'a thick, strong rope of wire, or a covered wire carrying electricity' },
  carry: { pos: 'verb', def: 'to hold something and take it from one place to another' },
  reach: { pos: 'verb', def: 'to stretch out your arm to get something, or to arrive at a place' },
  touch: { pos: 'verb', def: 'to put your hand or finger on something' },
  grasp: { pos: 'verb', def: 'to take hold of something firmly' },
  holds: { pos: 'verb', def: 'keeps something in your hands or arms, or has room for it' },
  moves: { pos: 'verb', def: 'changes position or goes from one place to another' },
  shift: { pos: 'verb', def: 'to move or change from one position to another' },
  slide: { pos: 'verb', def: 'to move smoothly over a surface' },
  glide: { pos: 'verb', def: 'to move smoothly and quietly, like a bird with still wings' },
  crawl: { pos: 'verb', def: 'to move slowly on your hands and knees' },
  march: { pos: 'verb', def: 'to walk with regular steps, like soldiers' },
  races: { pos: 'noun', def: 'contests of speed to see who is fastest' },
  walks: { pos: 'verb', def: 'moves along on foot at a steady pace' },
  steps: { pos: 'noun', def: 'single movements of the foot, or flat surfaces of a staircase' },
  chant: { pos: 'verb', def: 'to repeat words or sounds over and over in a rhythm' },
  shout: { pos: 'verb', def: 'to say something very loudly' },
  noise: { pos: 'noun', def: 'a loud or unpleasant sound' },
  drill: { pos: 'noun', def: 'a tool that makes holes by spinning a pointed bit' },
  screw: { pos: 'noun', def: 'a metal pin with a spiral ridge, twisted in to fasten things' },
  nails: { pos: 'noun', def: 'thin metal pins hammered in to join pieces of wood' },
  spray: { pos: 'verb', def: 'to scatter a liquid in tiny drops' },
  patch: { pos: 'noun', def: 'a piece of material put over a hole to mend it' },
  forge: { pos: 'noun', def: 'a workshop with a hot fire where metal is heated and shaped' },
  anvil: { pos: 'noun', def: 'a heavy iron block on which metal is hammered into shape' },
  torch: { pos: 'noun', def: 'a stick with a flame on the end, or a hand-held electric light' },
  flame: { pos: 'noun', def: 'the bright, hot tongue of light that rises from a fire' },
  smoke: { pos: 'noun', def: 'the gray cloud of gas and particles that rises from a fire' },
  ashes: { pos: 'noun', def: 'the gray powder left after something has burned' },
  blaze: { pos: 'noun', def: 'a large, fiercely burning fire' },
  flare: { pos: 'noun', def: 'a sudden bright burst of light, used as a signal' },
  shine: { pos: 'verb', def: 'to give out or reflect bright light' },
  gleam: { pos: 'noun', def: 'a soft, bright flash or glow of light' },
  rainy: { pos: 'adjective', def: 'having a lot of rain' },
  misty: { pos: 'adjective', def: 'covered with a thin cloud of tiny water droplets near the ground' },
  foggy: { pos: 'adjective', def: 'covered by thick cloud near the ground that makes it hard to see' },
  clips: { pos: 'noun', def: 'small fasteners that hold things together, or short pieces of a video' },
  sheet: { pos: 'noun', def: 'a large piece of cloth on a bed, or a flat thin piece of paper' },
  notes: { pos: 'noun', def: 'short written records of things to remember, or single musical tones' },
  essay: { pos: 'noun', def: 'a short piece of writing on a particular subject' },
  quote: { pos: 'verb', def: 'to repeat the exact words that someone else said or wrote' },
  index: { pos: 'noun', def: 'an alphabetical list at the back of a book showing where topics appear' },
  label: { pos: 'noun', def: 'a small piece of paper or cloth attached to an object to give information' },
  vault: { pos: 'noun', def: 'a strong, secure room for keeping valuables, usually in a bank' },
  taxes: { pos: 'noun', def: 'money people must pay to the government' },
  audit: { pos: 'noun', def: 'an official check of financial accounts to make sure they are correct' },
  asset: { pos: 'noun', def: 'something valuable that a person or company owns' },
  stock: { pos: 'noun', def: 'a supply of goods kept ready for sale, or a share in a company' },
  share: { pos: 'verb', def: 'to let someone else use or have part of what you have' },
  funds: { pos: 'noun', def: 'money available for a particular purpose' },
  loans: { pos: 'noun', def: 'sums of money lent to someone who must pay it back' },
  debit: { pos: 'noun', def: 'an entry showing money taken out of an account' },
  judge: { pos: 'noun', def: 'a public official who decides cases in a court of law' },
  trial: { pos: 'noun', def: 'a formal hearing in court to decide if someone broke the law' },
  crime: { pos: 'noun', def: 'an act that breaks the law' },
  guilt: { pos: 'noun', def: 'the feeling of having done something wrong, or the fact of breaking a law' },
  rules: { pos: 'noun', def: 'official instructions that say what you can and cannot do' },
  fines: { pos: 'noun', def: 'sums of money paid as punishment for breaking a law' },
  rugby: { pos: 'noun', def: 'a team sport played with an oval ball that can be carried and kicked' },
  relay: { pos: 'noun', def: 'a race in which team members take turns running parts of the course' },
  mixer: { pos: 'noun', def: 'a machine used to blend ingredients together' },
  blend: { pos: 'verb', def: 'to mix things together so they become one' },
  slice: { pos: 'noun', def: 'a thin, flat piece cut from a larger food item' },
  chops: { pos: 'noun', def: 'thick cuts of meat on a bone, usually from pork or lamb' },
  grate: { pos: 'verb', def: 'to shred food into small pieces by rubbing it on a rough surface' },
  crush: { pos: 'verb', def: 'to squash something so hard that it breaks or loses its shape' },
  mince: { pos: 'verb', def: 'to cut food into very small pieces' },
  whisk: { pos: 'verb', def: 'to beat eggs or cream quickly with a fork or a looped tool' },
  knead: { pos: 'verb', def: 'to press and fold dough with your hands to make it smooth' },
  steam: { pos: 'noun', def: 'the hot vapor given off by boiling water' },
  broth: { pos: 'noun', def: 'a thin soup made by simmering meat or vegetables in water' },
  honey: { pos: 'noun', def: 'a sweet, sticky golden food made by bees' },
  cream: { pos: 'noun', def: 'the thick, rich fatty part of milk' },
  crust: { pos: 'noun', def: 'the hard outer layer of bread or a pie' },
  crumb: { pos: 'noun', def: 'a tiny piece that falls off bread or cake' },
}
