import dictionaryText from './dictionary.txt?raw'

// 5-letter words from the MIT-licensed `an-array-of-english-words` package (v2.0.0).
export const DICTIONARY: Set<string> = new Set(dictionaryText.split('\n').filter(Boolean))

export const ANSWERS: string[] = [
  "apple", "chair", "sound", "world", "plant", "crane", "storm", "house", "mouse", "horse",
  "water", "paper", "table", "glass", "stone", "brick", "cloud", "river", "ocean", "beach",
  "grass", "bread", "sugar", "spice", "bacon", "candy", "lemon", "mango", "grape", "melon",
  "peach", "berry", "onion", "herbs", "shirt", "pants", "dress", "jeans", "socks", "scarf",
  "glove", "boots", "shoes", "cloak", "heart", "brain", "bones", "blood", "mouth", "teeth",
  "elbow", "wrist", "ankle", "thumb", "music", "piano", "dance", "drama", "movie", "novel",
  "story", "poems", "voice", "bring", "light", "night", "dream", "smile", "laugh", "tears",
  "happy", "angry", "quiet", "sharp", "blunt", "round", "small", "large", "giant", "heavy",
  "solid", "fresh", "clean", "dirty", "smell", "taste", "sweet", "spicy", "bland", "salty",
  "earth", "space", "orbit", "comet", "stars", "solar", "lunar", "globe", "peace", "anger",
  "brave", "proud", "shame", "faith", "trust", "doubt", "worry", "money", "bonus", "wages",
  "price", "value", "worth", "debts", "sales", "trade", "store", "cabin", "tower", "fence",
  "porch", "attic", "floor", "roofs", "walls", "rooms", "couch", "shelf", "clock", "lamps",
  "blind", "knife", "spoon", "plate", "bowls", "pizza", "sauce", "toast", "juice", "drink",
  "flour", "yeast", "dough", "baker", "maker", "clerk", "nurse", "actor", "teach", "learn",
  "study", "class", "grade", "exams", "tests", "books", "pages", "games", "chess", "board",
  "court", "score", "teams", "coach", "medal", "prize", "climb", "throw", "catch", "punch",
  "kicks", "block", "guard", "crazy", "funny", "silly", "weird", "scary", "lucky", "dizzy",
  "sorry", "sleep", "awake", "tired", "fruit", "olive", "beans", "beets", "curry", "gravy",
  "syrup", "metal", "steel", "brass", "crown", "queen", "reign", "royal", "noble", "lords",
  "baron", "sword", "armor", "spear", "arrow", "blade", "lance", "tiger", "eagle", "shark",
  "whale", "zebra", "camel", "sheep", "goats", "snake", "bunny", "puppy", "kitty", "otter",
  "koala", "panda", "bears", "foxes", "birds", "heron", "robin", "finch", "raven", "swans",
  "geese", "ducks", "quail", "trout", "perch", "squid", "crabs", "clams", "shell", "coral",
  "reefs", "waves", "tides", "lakes", "ponds", "creek", "delta", "shore", "mount", "hills",
  "cliff", "slope", "peaks", "ridge", "rocks", "sands", "dunes", "caves", "rains", "winds",
  "gusts", "frost", "snows", "sunny", "windy", "north", "south", "atlas", "route", "roads",
  "paths", "train", "plane", "buses", "truck", "wagon", "cycle", "metro", "ferry", "yacht",
  "bills", "coins", "cards", "bonds", "bench", "stool", "desks", "paint", "brush", "color",
  "shape", "shade", "tones", "black", "white", "green", "brown", "ivory", "beige", "amber",
  "khaki", "denim", "bored", "eager", "timid", "rough", "tough", "plain", "fancy", "cheap",
  "thick", "broad", "stale", "crisp", "juicy", "moist", "dried", "fried", "grill", "roast",
  "broil", "phone", "radio", "video", "photo", "robot", "laser", "drone", "motor", "wheel",
  "brake", "tires", "spark", "fuels", "power", "wires", "cable", "carry", "reach", "touch",
  "grasp", "holds", "moves", "shift", "slide", "glide", "crawl", "march", "races", "walks",
  "steps", "chant", "shout", "noise", "drill", "screw", "nails", "spray", "patch", "forge",
  "anvil", "torch", "flame", "smoke", "ashes", "blaze", "flare", "shine", "gleam", "rainy",
  "misty", "foggy", "clips", "sheet", "notes", "essay", "quote", "index", "label", "vault",
  "taxes", "audit", "asset", "stock", "share", "funds", "loans", "debit", "judge", "trial",
  "crime", "guilt", "rules", "fines", "rugby", "relay", "mixer", "blend", "slice", "chops",
  "grate", "crush", "mince", "whisk", "knead", "steam", "broth", "honey", "cream", "crust",
  "crumb",
]
